import { type NextPage } from "next";
import Head from "next/head";

const SinglePostPage: NextPage = () => {


  return (
    <>
      <Head>
        <title>Chirp | post </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div>
          post View
        </div>
      </main>
    </>
  );
};

export default SinglePostPage;
